name: akary
description: Best Way To Buy Or Sell Your  House

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^7.0.1
  flutter_offline: ^2.0.0
  google_sign_in: ^5.1.0
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  get: ^4.5.1
  get_storage: ^2.0.3
  flutter_facebook_auth: ^3.5.0
  shared_preferences: ^2.0.6
  introduction_screen: ^2.1.0
  carousel_slider: ^4.0.0
  csc_picker: ^0.2.6
  intl: ^0.17.0
  intl_phone_field: ^3.0.1
  image_picker: ^0.8.4+11
  map_picker: ^0.0.3
  geocoding: ^2.0.1
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.1.6
  flutter_rating_bar: ^4.0.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/
   - assets/images/
   - assets/data/
   - assets/translations/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
